# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', citx: cities.first)

Cell.destroy_all
Puzzle.destroy_all

Puzzle.create(name: 'House', x_size: 5, y_size: 5)
Puzzle.create(name: 'Superman', x_size: 10, y_size: 10)

Cell.create(y: 0, x: 2, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 1, x: 1, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 1, x: 2, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 1, x: 3, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 2, x: 0, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 2, x: 1, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 2, x: 2, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 2, x: 3, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 2, x: 4, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 3, x: 0, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 3, x: 1, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 3, x: 3, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 3, x: 4, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 4, x: 0, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 4, x: 1, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 4, x: 3, puzzle_id: Puzzle.find_by_name('House').id)
Cell.create(y: 4, x: 4, puzzle_id: Puzzle.find_by_name('House').id)

Cell.create(y: 1, x: 0, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 2, x: 0, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 3, x: 0, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 4, x: 0, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 5, x: 0, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 6, x: 0, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 7, x: 0, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 8, x: 0, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 0, x: 1, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 1, x: 1, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 2, x: 1, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 7, x: 1, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 8, x: 1, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 9, x: 1, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 0, x: 2, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 1, x: 2, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 3, x: 2, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 4, x: 2, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 5, x: 2, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 6, x: 2, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 8, x: 2, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 9, x: 2, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 0, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 1, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 3, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 4, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 5, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 6, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 7, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 8, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 9, x: 3, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 0, x: 4, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 1, x: 4, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 2, x: 4, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 6, x: 4, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 7, x: 4, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 8, x: 4, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 9, x: 4, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 1, x: 5, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 2, x: 5, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 3, x: 5, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 4, x: 5, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 5, x: 5, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 7, x: 5, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 8, x: 5, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 1, x: 6, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 2, x: 6, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 4, x: 6, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 5, x: 6, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 7, x: 6, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 8, x: 6, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 2, x: 7, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 3, x: 7, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 6, x: 7, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 7, x: 7, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 2, x: 8, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 3, x: 8, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 4, x: 8, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 5, x: 8, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 6, x: 8, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 7, x: 8, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 3, x: 9, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 4, x: 9, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 5, x: 9, puzzle_id: Puzzle.find_by_name('Superman').id)
Cell.create(y: 6, x: 9, puzzle_id: Puzzle.find_by_name('Superman').id)
